### ISSUE TITLE
Phpstorm IDE Build 222.* incompatible

### ISSUE THREAD

**Issue by fmay-lmwr** [sandronimus/toggl-intellij-plugin#1]
Hi Alexander,
Your awesome plugin isn't compatible with the latest version of Phpstorm :(
It's possible to fix it please?
tks a lot

**Comment by sandronimus** [comment]
Hi Frédéric!

Yes, I'll update plugin soon. Please wait a little.

**Comment by fmay-lmwr** [comment]
great!
thank you very much

**Comment by sandronimus** [comment]
Plugin updated. Thanks for using it!

**Comment by fmay-lmwr** [comment]
thanks you so much, it's work !!
